### PR TITLE
Contribute KEEBD Dumbpad OLED version

### PR DESCRIPTION
**Pull request by medoix**
It appears someones previous commit included this version from our fork into the README so i am raising a PR to commit the files up so the links work. I can also add the firmware via a PR is it helps.

The main changes in this ```combo_oled``` version is the replacement of the LED's and resistors for a single OLED display that can be programmed to show all of the relevant layer info plus more.

### CODE REVIEW

**Comment by medoix** [comment]
@deveth0 @imchipwood

**Comment by deveth0** [comment]
Ouch, my fault 🗡️ 

Thanks for the finding and the contribution, could you probably add one or two images to the README?

**Comment by medoix** [comment]
No worries it reminded me to push this upstream. I have added a README with images.

**Comment by deveth0** [comment]
love it <3 

probably i'll need to make a dumbpad_oled_rgb next? :D

**Comment by medoix** [comment]
I had that exact same thought, maybe we can collab on that to make the worlds best dumbpad 😆

**Comment by imchipwood** [comment]
I love open source - thanks to both of you for contributing!

I'll review this some time this week, might even be time for me to learn
kicad..

**Comment by imchipwood** [comment]
image

Opened the schematic with kicad 6.x and was presented with an error about a missing drawing sheet - should this be included somewhere?

Other than that, I approve!

**Comment by medoix** [comment]
> image
> 
> Opened the schematic with kicad 6.x and was presented with an error about a missing drawing sheet - should this be included somewhere?
> 
> Other than that, I approve!

Good catch, i believe i have fixed that issue now.

**Pull request merged**
